apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-app-external-secret
  namespace: default # must match SecretStore
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: my-app-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: slack-api-key
      remoteRef:
        key: slackApiKey
        property: slack-api-key
