apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: ex-test
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: PORT
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: USER
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: connection-string
            - name: SLACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: slack-secret # Name of the k8s secret from ExternalSecret.yaml
                  key: slack-api-key
            - name: GREENHOUSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: greenhouse-secret # Name of the k8s secret from ExternalSecret.yaml
                  key: greenhouse-api-key
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
