apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-ss
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount
